### ISSUE TITLE
How about documentation ?

### ISSUE THREAD

**Issue by iyarsius** [vaariance/variance-dart#16]
Hey, i just read the readme and this package could be very helpful for me, i was looking exactly this type of package. Unfortunately, the doc is empty so idk if it's cause the project is abandoned or if it's just releasing soon.

**Comment by code-z2** [comment]
Thanks for flagging that, We are pretty much working on rewriting our docs. Which would surely be out in the next couple of weeks. The code is still on active development.

**Comment by iyarsius** [comment]
ok great, keep up the amazing work !

**Comment by code-z2** [comment]
https://docs.variance.space
